export const planetsArray: string[] = [
  'Alphabetrium',
  'Arboles Mentirosos',
  'Big Pluto',
  'Biggum',
  'Bird World',
  'Boob World',
  'Cronenberg World',
  'Crustula',
  'Delphi 6',
  'Dorian 5',
  'Dwarf Terrace-9',
  'Earth',
  'Flarbellon-7',
  'Flump',
  'Forbodulon Prime',
  'Fran Dreslicar',
  'Gaia',
  'Gazorpazorp',
  'Gear World',
  'Glapflap',
  'Glorfingr 7',
  'Gramuflack',
  'Granitor 7',
  'Gromflom Prime',
  'Krootabulon',
  'Krumpf',
  'M-9999',
  'Nebraska (the planet)',
  'On a Cob Planet',
  'Parblesnops',
  'Pawn Shop Planet',
  'Planet MWA739',
  'Planet Squanch',
  'Pluto',
  'Purge Planet',
  'Resort planet',
  'Screaming Sun Earth',
  'Shongi the Living Planet',
  'Snake Planet',
  'Snorlab',
  'Spikky Remis',
  'Terraneous system',
  'Timbus',
  'Trumpdorian planet',
  'Tryonicon-5',
  "Unity's Planet",
  'Venzenulon 7',
  'Venzenulon 9',
  'Windshield Washing Planet',
  'Yarple-7',
  'Zipple',
  'Zorpantheon 9',
];

export const RegExpEmailValidation =
  /^(([^<>()[\]\.,;:\s@\"]+(\.[^<>()[\]\.,;:\s@\"]+)*)|(\".+\"))@(([^<>()[\]\.,;:\s@\"]+\.)+[^<>()[\]\.,;:\s@\"]{2,})$/i;

export const RegExpImageValidation = /.+(\.jpg|\.jpeg|\.gif|\.png)$/i;

export const modalCard = false;
